layout_spectrum: 0.6905160494163485
typography_spectrum: 0.7144638851362437
color:
  lightness: 0.6333741747743754
  brandColors:
    - '#405952'
    - '#9C9B7A'
    - '#FFD393'
    - '#FF974F'
    - '#F54F29'
  saturation: 0.6029518856311973
  brandStrength: 0.03312719734311841
  rhythmicContrast: 0.3728133062774887
coverPrefs:
  filter: false
name: Dr. Adrian Low
analytics: {}
github: true
author:
  name: DrAdrianLow
  email: adrian.low@live.hk
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
title: Dr. Adrian Low
description: 'Author, Researcher, Psychologist'
purpose:
  - type: contact
    url: 'mailto:adrian.low@adtigo.com'
    label: Contact me
  - type: external
    url: 'http://www.adtigokids.com'
    label: Kids Courses
